### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by kn-neelalohitha** [adobe/opentsdb-protector#2]
### What happened?
I wanted use opentsdb-protector tool for my project involving time series data. While reading [README.md](https://github.com/adobe/opentsdb-protector/blob/master/README.md) I found a typo and minor case inconsistency in [introduction](https://github.com/adobe/opentsdb-protector#introduction) section
### Expected Behaviour
**NA**
### Actual Behaviour
**NA**
### Reproduce Scenario (including but not limited to)
https://github.com/adobe/opentsdb-protector#introduction
#### Steps to Reproduce
**NA**
#### Platform and Version
**NA**
#### Sample Code that illustrates the problem
**NA**
#### Logs taken while reproducing problem
**NA**

**Comment by mynerva** [comment]
PR merged, you can close this one

**Comment by kn-neelalohitha** [comment]
Thanks @mynerva! Fix: PR #3
